image: node:latest

stages:
  - test
  - production

test:
  type: test
  stage: test
  image: ruby:latest
  script:
    - gem install npm
    - npm i
    - npm run test
  only:
    - development

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY_FALAH
  only:
    - development
